from decouple import AutoConfig

dconfig = AutoConfig()

DATABASE_TYPE = dconfig("DATABASE_TYPE")
DATABASE_USER = dconfig("DATABASE_USER")
DATABASE_PASSWORD = dconfig("DATABASE_PASSWORD")
DATABASE_HOST = dconfig("DATABASE_HOST")
DATABASE_NAME = dconfig("DATABASE_NAME")
PROJECT_DIR = dconfig("PROJECT_DIR")
TEMP_FORECAST_BUCKET_NAME=dconfig("TEMP_FORECAST_BUCKET_NAME")
TEMP_HISTORICAL_BUCKET_NAME=dconfig("TEMP_HISTORICAL_BUCKET_NAME")
GENERAL_BUCKET_NAME=dconfig("GENERAL_BUCKET_NAME")
DEMAND_BUCKET_NAME=dconfig("DEMAND_BUCKET_NAME")
DATABASE_STRING = f"{DATABASE_TYPE}://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}/{DATABASE_NAME}"
DEMAND_DOCKER_IMAGE=dconfig("DEMAND_DOCKER_IMAGE")